root = "."
tmp_dir = "tmp"

[build]
bin = "tmp/main"
cmd = "go build -o tmp/main cmd/main.go"
exclude_dir = ["assets", "tmp", "vendor", "testdata", "web"]
exclude_regex = ["_test.go"]
include_ext = ["go", "tpl", "tmpl", "html"]
log = "build-errors.log"

[color]
build = "yellow"
main = "magenta"
runner = "green"
watcher = "cyan"

[screen]
keep_scroll = true
