services:
  daily-menu:
    build: 
      context: .
      dockerfile: Dockerfile
      cache_from:
        - golang:1.24-alpine
        - alpine:latest
    ports:
      - "3030:3030"
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://localhost:3030/"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    env_file:
      - .env
    environment:
      - GIN_MODE=release
    security_opt:
      - no-new-privileges:true
    tmpfs:
      - /tmp
    volumes:
      - daily-menu-data:/app/database

volumes:
  daily-menu-data: