# Name of your application. Used to uniquely configure containers.
service: daily-menu
image: artyomkalman/daily-menu

servers:
  web:
    - artyomkalashnikov.ru

proxy:
  ssl: true
  host: menu.artyomkalashnikov.ru
registry:
  username: artyomkalman
  password:
    - KAMAL_REGISTRY_PASSWORD

builder:
  arch: amd64

env:
  clear:
    PORT: 80
    PEONY_URL: https://kbu.ac.kr/kor/CMS/DietMenuMgr/list.do?mCode=MN203&searchDietCategory=4
    AZILEA_URL: https://kbu.ac.kr/kor/CMS/DietMenuMgr/list.do?mCode=MN203&searchDietCategory=5
  secret:
    - GPT_URL
    - GPT_TOKEN
    - TELEGRAM_BOT

ssh:
  user: artyom

